<?php

declare(strict_types=1);

namespace CoolMS\Core\Application\Tests\ApiManifest;

use CoolMS\Core\Application\Tests\ApiManifest\Fixture\SectionsManifestContributor;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;

/**
 * `ApiManifestPatternTrait` lets a manifest contributor publish an item route
 * as a pattern, `/api/v1/sections/{id}`, rather than as one generated URL: the
 * route is generated with a placeholder value, and the placeholder is then
 * swapped for the bare `{param}` token a client fills in.
 *
 * The URL generator percent-encodes parameter values, so the swap looks for the
 * placeholder in its encoded form.
 *
 * The fixture is the consumer's shape: a contributor that generates its
 * collection routes plainly and its item routes through the trait. The routes
 * are real, generated by Symfony's own URL generator.
 */
final class ApiManifestPatternTraitTest extends TestCase
{
    #[Test]
    public function eachItemRouteIsPublishedAsAPatternWithTheTokenWhereTheIdGoes(): void
    {
        [$key, $manifest] = new SectionsManifestContributor($this->urlGenerator())->contribute();

        self::assertSame('sections', $key);
        self::assertSame('/api/v1/sections/{id}', $manifest->item);
        self::assertSame('/api/v1/sections/{id}', $manifest->update);
        self::assertSame('/api/v1/sections/{id}/trash', $manifest->delete);
    }

    #[Test]
    public function collectionRoutesGeneratedAlongsideAreLeftAsTheyAre(): void
    {
        [, $manifest] = new SectionsManifestContributor($this->urlGenerator())->contribute();

        self::assertSame('/api/v1/sections', $manifest->list);
        self::assertSame('/api/v1/sections/new', $manifest->create);
    }

    /**
     * The first assertion is the control: it shows the generator really does
     * encode this placeholder, so the case below is not passing by accident.
     */
    #[Test]
    public function aPlaceholderTheGeneratorPercentEncodesIsStillReplaced(): void
    {
        $urlGenerator = $this->urlGenerator();
        self::assertSame('/api/v1/sections/%7Bid%7D', $urlGenerator->generate('sections_get', ['id' => '{id}']));

        [, $manifest] = new SectionsManifestContributor($urlGenerator, '{id}')->contribute();

        self::assertSame('/api/v1/sections/{id}', $manifest->item);
    }

    private function urlGenerator(): UrlGenerator
    {
        $routes = new RouteCollection();
        $routes->add('sections_list', new Route('/api/v1/sections'));
        $routes->add('sections_create', new Route('/api/v1/sections/new'));
        $routes->add('sections_get', new Route('/api/v1/sections/{id}'));
        $routes->add('sections_update', new Route('/api/v1/sections/{id}'));
        $routes->add('sections_delete', new Route('/api/v1/sections/{id}/trash'));

        return new UrlGenerator($routes, new RequestContext());
    }
}
